# Generated by jeweler
# DO NOT EDIT THIS FILE DIRECTLY
# Instead, edit Jeweler::Tasks in Rakefile, and run 'rake gemspec'
# -*- encoding: utf-8 -*-

Gem::Specification.new do |s|
  s.name = "chromembed_rails"
  s.version = "0.2.1"

  s.required_rubygems_version = Gem::Requirement.new(">= 0") if s.respond_to? :required_rubygems_version=
  s.authors = ["Victor Costan"]
  s.date = "2012-04-14"
  s.description = "Ruby on Rails engine for Web applications that are strongly coupled with Chrome extensions"
  s.email = "costan@gmail.com"
  s.extra_rdoc_files = [
    "LICENSE.txt",
    "README.rdoc"
  ]
  s.files = [
    ".project",
    "Gemfile",
    "Gemfile.lock",
    "LICENSE.txt",
    "README.rdoc",
    "Rakefile",
    "VERSION",
    "chromembed_rails.gemspec",
    "lib/chromembed_rails.rb",
    "lib/chromembed_rails/controller.rb",
    "lib/chromembed_rails/engine.rb",
    "lib/chromembed_rails/generators/all_generator.rb",
    "lib/chromembed_rails/generators/templates/001_create_chrome_extension_caches.rb",
    "lib/chromembed_rails/generators/templates/chrome_extension_cache.rb",
    "lib/chromembed_rails/generators/templates/chrome_extension_caches.yml",
    "lib/chromembed_rails/generators/templates/chrome_extension_controller.rb",
    "lib/chromembed_rails/generators/templates/chrome_extension_controller_test.rb",
    "lib/chromembed_rails/generators/templates/chrome_extension_initializer.rb",
    "lib/chromembed_rails/generators/templates/desktop/chrome_extension.pem.erb",
    "lib/chromembed_rails/generators/templates/desktop/chrome_extension/images/ruby128.png",
    "lib/chromembed_rails/generators/templates/desktop/chrome_extension/images/ruby16.png",
    "lib/chromembed_rails/generators/templates/desktop/chrome_extension/images/ruby19.png",
    "lib/chromembed_rails/generators/templates/desktop/chrome_extension/manifest.json",
    "lib/chromembed_rails/model.rb",
    "lib/chromembed_rails/routes.rb",
    "test/chrome_extension_cache_test.rb",
    "test/chrome_extension_controller_test.rb",
    "test/helpers/application_controller.rb",
    "test/helpers/chrome_extension.pem",
    "test/helpers/db_setup.rb",
    "test/helpers/initializers.rb",
    "test/helpers/routes.rb",
    "test/routes_test.rb",
    "test/test_helper.rb"
  ]
  s.homepage = "http://github.com/pwnall/chromembed_rails"
  s.licenses = ["MIT"]
  s.require_paths = ["lib"]
  s.rubygems_version = "1.8.22"
  s.summary = "Serves a Chrome extension embedded in a Rails application"

  if s.respond_to? :specification_version then
    s.specification_version = 3

    if Gem::Version.new(Gem::VERSION) >= Gem::Version.new('1.2.0') then
      s.add_runtime_dependency(%q<crxmake>, [">= 2.0.7"])
      s.add_runtime_dependency(%q<rails>, [">= 3.1.1"])
      s.add_development_dependency(%q<bundler>, [">= 1.1.0"])
      s.add_development_dependency(%q<jeweler>, [">= 1.8.3"])
      s.add_development_dependency(%q<mocha>, [">= 0.9.12"])
      s.add_development_dependency(%q<sqlite3>, [">= 1.3.5"])
    else
      s.add_dependency(%q<crxmake>, [">= 2.0.7"])
      s.add_dependency(%q<rails>, [">= 3.1.1"])
      s.add_dependency(%q<bundler>, [">= 1.1.0"])
      s.add_dependency(%q<jeweler>, [">= 1.8.3"])
      s.add_dependency(%q<mocha>, [">= 0.9.12"])
      s.add_dependency(%q<sqlite3>, [">= 1.3.5"])
    end
  else
    s.add_dependency(%q<crxmake>, [">= 2.0.7"])
    s.add_dependency(%q<rails>, [">= 3.1.1"])
    s.add_dependency(%q<bundler>, [">= 1.1.0"])
    s.add_dependency(%q<jeweler>, [">= 1.8.3"])
    s.add_dependency(%q<mocha>, [">= 0.9.12"])
    s.add_dependency(%q<sqlite3>, [">= 1.3.5"])
  end
end

